# clean base image containing only comfyui, comfy-cli and comfyui-manager
FROM runpod/worker-comfyui:5.8.4-base

# build-time tokens for gated downloads — never baked into final image.
# pass via: docker build --build-arg HF_TOKEN=$HF_TOKEN ...
ARG HF_TOKEN=""

# install custom nodes into comfyui
RUN comfy node install --exit-on-fail gguf@2.3.5 --mode remote || (echo "WARN: gguf@2.3.5 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail gguf --mode remote)
RUN comfy node install --exit-on-fail comfyui-easy-use@1.3.1 || (echo "WARN: comfyui-easy-use@1.3.1 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-easy-use)
RUN comfy node install --exit-on-fail comfyui-kjnodes@1.1.3 || (echo "WARN: comfyui-kjnodes@1.1.3 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-kjnodes)
RUN comfy node install --exit-on-fail comfyui-frame-interpolation@1.0.7 || (echo "WARN: comfyui-frame-interpolation@1.0.7 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-frame-interpolation)
RUN comfy node install --exit-on-fail comfyui-ollama@2.0.6 || (echo "WARN: comfyui-ollama@2.0.6 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-ollama)
RUN comfy node install --exit-on-fail comfyui-levelpixel@1.2.8 || (echo "WARN: comfyui-levelpixel@1.2.8 unavailable in registry, falling back to latest" >&2 && comfy node install --exit-on-fail comfyui-levelpixel)

# download models into comfyui
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/calcuis/pig-vae/resolve/main/pig_wan_vae_fp32-f16.gguf' --relative-path models/vae --filename 'pig_wan_vae_fp32-f16.gguf' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/bullerwins/Wan2.2-I2V-A14B-GGUF/resolve/main/wan2.2_i2v_low_noise_14B_Q4_K_M.gguf' --relative-path models/diffusion_models --filename 'wan2.2-i2v-14b-low-noise-q4_k_m.gguf' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/bullerwins/Wan2.2-I2V-A14B-GGUF/resolve/main/wan2.2_i2v_high_noise_14B_Q4_K_M.gguf' --relative-path models/diffusion_models --filename 'wan2.2-i2v-14b-high-noise-q4_k_m.gguf' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Aitrepreneur/FLX/resolve/main/Wan2.2-Lightning_I2V-A14B-4steps-lora_HIGH_fp16.safetensors' --relative-path models/loras --filename 'wan_loras/Wan2.2-Lightning_I2V-A14B-4steps-lora_HIGH_fp16.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/LoRAs/Wan22-Lightning/old/Wan2.2-Lightning_I2V-A14B-4steps-lora_LOW_fp16.safetensors' --relative-path models/loras --filename 'wan_loras/Wan2.2-Lightning_I2V-A14B-4steps-lora_LOW_fp16.safetensors' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/city96/umt5-xxl-encoder-gguf/resolve/0e9a7657447c3a2215edf3a7c5a081633102d19c/umt5-xxl-encoder-Q4_K_M.gguf' --relative-path models/diffusion_models --filename 'umt5-xxl-encoder-q4_k_m.gguf' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
RUN BACKOFFS="10 20 30 60 90" && for i in 1 2 3 4 5; do HF_TOKEN=$HF_TOKEN comfy model download --url 'https://huggingface.co/hfmaster/models-moved/resolve/e079d17b516944ea0401734637f4c7c81434cfa4/rife/rife49.pth' --relative-path models/frame_interpolation --filename 'rife49.pth' && break; if [ $i -eq 5 ]; then echo "model-download failed after 5 attempts" >&2; exit 1; fi; SLEEP=$(echo $BACKOFFS | cut -d ' ' -f $i) && echo "model-download attempt $i failed; retrying in $SLEEP seconds" >&2; sleep $SLEEP; done
